name: Build and Deploy to Azure Container

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: azure/docker-login@v1
      with:
        login-server: todolistacr.azurecr.io
        username: ${{ secrets.REGISTRY_USERNAME }}
        password: ${{ secrets.REGISTRY_PASSWORD }}
    - run: |
        docker build . -t todolistacr.azurecr.io/todolist-frontend:${{ github.sha }}
        docker push todolistacr.azurecr.io/todolist-frontend:${{ github.sha }}
